"""agrega tablas de carrito

Revision ID: a1a3bcfa6d2b
Revises: 5d22d92828be
Create Date: 2026-01-25 20:04:17.662379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a3bcfa6d2b'
down_revision: Union[str, Sequence[str], None] = '5d22d92828be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
